services:
  api:
    build:
      context: ..
      dockerfile: ./deployments/docker/dockerfile.lift-simulation
      args:
        BUILD_REF: ${VERSION}
        BUILD_DATE: ${BUILD_DATE}
        ENV: ${ENV:-development}
    image: ${BASE_IMAGE_NAME}/${LS_APP}:${VERSION}
    container_name: lift-simulation-api
    restart: always
    ports:
      - "${API_PORT:-80}:${INSIDE_PORT:-8080}"
    env_file:
      - ../src/.env.${ENV:-development}
    environment:
      - API_PORT=${API_PORT:-80}
      - INSIDE_PORT=${INSIDE_PORT:-8080}
      - GO_ENV=${ENV:-development}
    volumes:
      - lift-sim-db:/app/db
    networks:
      - app-tier

  # redis:
  #   image: bitnami/redis:latest
  #   container_name: redis
  #   restart: always
  #   ports:
  #     - "${REDIS_PORT:-6379}:${REDIS_PORT:-6379}"
  #   command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
  #   volumes:
  #     - redis-data:/data
  #   env_file:
  #     - ../src/.env
  #   environment:
  #     - REDIS_PORT=${REDIS_PORT:-6379}
  #     - REDIS_PASSWORD=${REDIS_PASSWORD:-redispassword}
  #   networks:
  #     - app-tier

networks:
  app-tier:
    driver: bridge
volumes:
  lift-sim-db:
    driver: local
#   redis-data:
#     driver: local
