services:
  api:
    build:
      context: ..
      dockerfile: ./deployments/docker/dockerfile.lift-simulation
      args:
        BUILD_REF: ${VERSION}
        BUILD_DATE: ${BUILD_DATE}
        ENV: ${ENV:-development}
    image: ${BASE_IMAGE_NAME}/${LS_APP}:${VERSION}
    container_name: lift-simulation-api
    restart: always
    ports:
      - "${HTTP_PORT:-80}:${INSIDE_HTTP_PORT:-8080}"
      - "${HTTPS_PORT:-443}:${INSIDE_HTTPS_PORT:-8443}"
    env_file:
      - ../src/.env.${ENV:-development}
    environment:
      - HTTP_PORT=${HTTP_PORT:-80}
      - HTTPS_PORT=${HTTPS_PORT:-443}
      - INSIDE_HTTP_PORT=${INSIDE_HTTP_PORT:-8080}
      - INSIDE_HTTPS_PORT=${INSIDE_HTTPS_PORT:-8443}
      - GO_ENV=${ENV:-development}
      - CERT_FILE=${CERT_FILE:-/certs/fullchain.pem}
      - KEY_FILE=${KEY_FILE:-/certs/privkey.pem}
    volumes:
      - lift-sim-db:/db
      - ../src/certs:/certs:ro
    networks:
      - app-tier

  # redis:
  #   image: bitnami/redis:latest
  #   container_name: redis
  #   restart: always
  #   ports:
  #     - "${REDIS_PORT:-6379}:${REDIS_PORT:-6379}"
  #   command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
  #   volumes:
  #     - redis-data:/data
  #   env_file:
  #     - ../src/.env
  #   environment:
  #     - REDIS_PORT=${REDIS_PORT:-6379}
  #     - REDIS_PASSWORD=${REDIS_PASSWORD:-redispassword}
  #   networks:
  #     - app-tier

networks:
  app-tier:
    driver: bridge

volumes:
  lift-sim-db:
    driver: local
  # redis-data:
  #   driver: local
