services:
  redis:
    image: bitnami/redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass redispassword
    volumes:
      - redis-data:/data
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge

volumes:
  redis-data:
    driver: local
