name: Go CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  GO_VERSION: "1.23"
  AWS_REGION: "us-east-2"
  DOCKER_USERNAME: "avyukth"

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Generate CI environment file
        run: |
          chmod +x ./scripts/generate_env.sh
          ./scripts/generate_env.sh
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
          GO_ENV: ci

      - name: Run tests
        run: |
          cd src
          go test -v ./...

      - name: Build
        run: |
          cd src
          go build -v ./...

  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set short SHA
        run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-8)" >> $GITHUB_ENV

      - name: Generate CI environment file
        run: |
          chmod +x ./scripts/generate_env.sh
          ./scripts/generate_env.sh
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
          GO_ENV: ci

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./deployments/docker/dockerfile.lift-simulation
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/lift-simulation:${{ env.SHORT_SHA }}
          build-args: |
            BUILD_REF=${{ env.SHORT_SHA }}
            BUILD_DATE=${{ github.event.repository.updated_at }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: docker
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set short SHA
        run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-8)" >> $GITHUB_ENV

      - name: Generate production environment file
        run: |
          chmod +x ./scripts/generate_env.sh
          ./scripts/generate_env.sh
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
          GO_ENV: production

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to EC2
        env:
          EC2_IP: ${{ secrets.EC2_IP }}
        run: |
          echo "Deploying to EC2 (Production Environment)..."
          scp -i ${{ secrets.EC2_SSH_KEY }} -o StrictHostKeyChecking=no .env.generated ubuntu@$EC2_IP:/home/ubuntu/lift-simulation.env
          ssh -i ${{ secrets.EC2_SSH_KEY }} -o StrictHostKeyChecking=no ubuntu@$EC2_IP << EOF
            docker pull ${{ env.DOCKER_USERNAME }}/lift-simulation:${SHORT_SHA}
            docker stop lift-simulation || true
            docker rm lift-simulation || true
            docker run -d --name lift-simulation -p 80:8080 \
              --env-file /home/ubuntu/lift-simulation.env \
              lift-simulation:${SHORT_SHA}
          EOF
